on: [push]

jobs:
  hello_job:
    runs-on: ubuntu-latest
    environment: staging
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-buildx-action@v1
    - uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        load: true
        secrets: ${{ secrets }}
