name: Hello from secret

on:
  push:
    branches: [ "staging" ]

jobs:
  hello:
    runs-on: ubuntu-latest
    environment: staging
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-buildx-action@v1
    - uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        load: true
        tags: |
          hello-from-secrets
        cache-from: type=gha
        cache-to: type=gha,mode=max
        #${{ secrets.SERVICE_ACCOUNT_CREATE_PEM }}
        secrets: |
          SERVICE_ACCOUNT_CREATE_PEM="${{ secrets.SERVICE_ACCOUNT_CREATE_PEM }}"
          SERVICE_ACCOUNT_BACKUP_PEM="def"
    - name: Run hello
      run: docker run --name hello-from-secrets hello-from-secrets

